version: 2.1

jobs:
  build: # this can be any name you choose
    docker:
      - image: node:18
    resource_class: large
    parallelism: 2

    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-8 --activate
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
    #   - run:
    #       name: Run Lint
    #       command: scripts/lint.sh
    #   - run:
    #       name: Run Tests
    #       command: npm run test
    #   - run:
    #       name: Report Coverage
    #       command: bash <(curl -s https://codecov.io/bash)
    #   - store_test_results:
    #         path: coverage
