version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Packages
          command: npm install
      - run:
          name: Run Lint
          command: scripts/lint.sh
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Report Coverage
          command: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
            path: test-results
workflows:
    version: 2
    test_flow:
        jobs:
            - build
