version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Packages
          command: npm install
      - run:
          name: Run Lint
          command: npm run lint && false
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Report Coverage
          command: bash <(curl -s https://codecov.io/bash)
