version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Packages
          command: npm install
  lint:
    machine: true
      steps:
        - run:
          name: Run Lint
          command: npm run lint
