on:
  push:
    branches: [master]

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-20.04
    timeout-minutes: 8
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: spectre-react-lib

      - run: echo "Releases created ${{ steps.release.outputs.releases_created }}"

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}
      - uses: pnpm/action-setup@v4
        with:
          version: 8
        if: ${{ steps.release.outputs.releases_created }}
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
        if: ${{ steps.release.outputs.releases_created }}
      - name: Install dependencies
        run: pnpm install
        if: ${{ steps.release.outputs.releases_created }}
      - name: Build
        run: pnpm build
        if: ${{ steps.release.outputs.releases_created }}
      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.releases_created  }}
      - name: Publish
        run: pnpm publish --no-git-checks --access public
        if: ${{ steps.release.outputs.releases_created  }}
