on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-20.04
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: spectre-react-lib

      - run: echo "Releases created ${{ steps.release.outputs.releases_created }}"

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.releases_created }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
        if: ${{ steps.release.outputs.releases_created }}
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
        if: ${{ steps.release.outputs.releases_created }}
      - name: Install dependencies
        run: pnpm install
        if: ${{ steps.release.outputs.releases_created }}
      - name: Build
        run: pnpm build
        if: ${{ steps.release.outputs.releases_created }}
      - name: Publish
        run: pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.releases_created  }}
