name: Bun Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  bun-test:
    name: bun-test
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun test --coverage
