name: Type Checking

on: pull_request

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1.1.0

      - run: bun install
      - run: bun run tsc
